### PR TITLE
Have init script create and chown the pid run dir.

### PR DESCRIPTION
**Pull request by alex-harvey-z3q**

### CODE REVIEW

**Comment by alex-harvey-z3q** [comment]
I added in some commits to clean up the code a bit too - I fixed the issue that unwanted newlines are being inserted in the init script and moved to the newer, [preferred](https://docs.puppetlabs.com/puppet/latest/reference/lang_template_erb.html#scopevariable-or-scopelookupvarvariable) scope syntax.

**Comment by alex-harvey-z3q** [comment]
OK.  I added a quick fix for Issue #45 as well.  I suspect this is what @walterheck originally intended?

**Comment by alex-harvey-z3q** [comment]
@lesaux  Any chance I could get this PR reviewed?

**Comment by lesaux** [comment]
Ok I can merge this for now, but I don't consider the issue completely solved.

I'm guessing elastic will release a startup script in their package someday, and https://github.com/elastic/kibana/issues/4680 definitely needs to be addressed. If a process is running, it should have a pidfile and it shouldn't matter if it is able to connect to ES or not.

**Pull request merged**
