### PR TITLE
add proxy support for package installations

### PR DESCRIPTION
**Pull request by tosmi**
- use https uri's in .fixtures
- support proxy when using packages
- minimal fixes to make puppet-lint happier

### CODE REVIEW

**Comment by tosmi** [comment]
hm, the failing tests are strange. i didnt' touch the travis config and bundler would like to install google-api-client which requires ruby > 1.9.3. my guess is that beaker has a dependency on google-api ,so maye we should run `bundler --without=system_tests`?

**Comment by lesaux** [comment]
Hi @tosmi,

Thanks for your work.

I am wondering if the http proxy config in yum should be set globally with the help of another module, but 
I can also imagine some cases when your other repos don't need a proxy, so this might still be relevant.

It's unfortunate we can't provide the same ability with the apt repo. I don't like the idea of having a feature not shared across distros.

Nevertheless I think I will merge it as soon a we figure out what exactly is wrong with Travis.

**Comment by tosmi** [comment]
setting a global yum option is possible but wouldn't help in our case. we've got mirrors for some repos which are only reachable without a proxy. so we need the possibility to set the proxy on a per repo basis.

we could solve this via a resource collector in a profile, but from our view it seems to be easier and more understandable to support a proxy directly in the module.

thanks
toni

**Comment by lesaux** [comment]
Hi @tosmi,

Looks like the tests are working again.
Would you mind rebasing from master? I would like to merge.

**Comment by tosmi** [comment]
ok, thanks. will do today.

**Comment by tosmi** [comment]
i've rebased the `itsallaboutproxies` branch on the current master, tests are also ok.

thanks
toni

**Comment by lesaux** [comment]
Thanks @tosmi!

**Pull request merged**
