### PR TITLE
Systemd support

### PR DESCRIPTION
**Pull request by madAndroid**
Addresses #50

### CODE REVIEW

**Comment by lesaux** [comment]
Hi MadAndroid.

Thanks for this. I was wondering if we were to run ES on a different server than Kibana, but it seems After= dependency is only effective when service including After= and service included by After= are both scheduled to start as part of your boot up, so we should be fine.

Seems like everyone is moving away from scope.lookup as well.

Also there is no more kibana4::pid_file parameter anymore, we should get it from the config hash.

This is what we are doing in the init.d template

```
<% if scope['kibana4::config'].is_a?(Hash) and scope['kibana4::config'].has_key?('pid_file') -%>
pidfile=<%= scope['kibana4::config']['pid_file'] -%>
<% elsif scope['kibana4::config'].is_a?(Hash) and scope['kibana4::config'].has_key?('pid.file') -%>
pidfile=<%= scope['kibana4::config']['pid.file'] -%>
<% else -%>
pidfile=/var/run/kibana.pid
<% end -%>
```

**Comment by madAndroid** [comment]
> Also there is no more kibana4::pid_file parameter anymore, we should get it from the config hash.

Ah, okay .. didn't notice that, thanks for pointing it out .. will change that asap :)

**Comment by lesaux** [comment]
The whole pid.file/pid_file thing is hard to deal with. Frankly it feels like we're trying to fix a software bug with puppet.
See https://github.com/lesaux/puppet-kibana4/issues/52 and https://github.com/elastic/kibana/issues/4680

**Comment by MEPhoenyx** [comment]
Hello,

I use your module with Debian Jessie.
And to this service start everything works.

According params.pp he makes a query for the Fact operating system and sets service_provider = debian

But I still get the message again and again:

Error: / Stage [main] / Kibana4 :: Service / Service [kibana4]: Provider init is not functional on this host

What am I doing wrong? I hope you can help me. Or have i understand false this merge request.

Thats all what i do:

```
class { '::kibana4':
   config              => {
        'server.port'           => 5601,
        'server.host'           => '0.0.0.0',
        'elasticsearch.url'     => "${elasticurl}:9200",
        }
  }
```

Thx Martin

**Comment by lesaux** [comment]
Hi MEPhoenyx,

You're right. I just added a beaker test for Debian Jessie and there seems to be an issue with starting the service. I'll take a look.

**Comment by MEPhoenyx** [comment]
Hello @lesaux,  you found a solution for the problem with systemd, or can I support you anyway, for example with a workaround for inspiration.

**Comment by lesaux** [comment]
kibana package 4.5 now supports systemd. I'll provide an update shortly.

**Comment by lesaux** [comment]
I've released a new module version. Version 4.5 packages now provide systemd support.

**Pull request closed without merging**
