### PR TITLE
add Kibana config file template as parameter

### PR DESCRIPTION
**Pull request by stivio**
hello, it will be very nice to have opportunity to use custom template for kibana.yml

### CODE REVIEW

**Comment by lesaux** [comment]
Hi, I will be doing this slightly differently in PR #36 

Please let me know your opinion.

**Comment by stivio** [comment]
Good dicision!!
What do you think about switching from scope to @varname syntax at templates ?Because scope sometimes have strange behavior from version to version of puppet

**Comment by lesaux** [comment]
I'm not sure what you mean. Would you know of an example you could refer me to?

**Comment by stivio** [comment]
I'm add examples , please look https://github.com/stivio/puppet-kibana4/commit/b240c56b7752f9ebd8fa9cc544a7e0eb13844ade

**Comment by lesaux** [comment]
closing as this was fixed in another pr

**Pull request closed without merging**
