### PR TITLE
Issue_53  Add package_dl_timeout feature

### PR DESCRIPTION
**Pull request by alex-harvey-z3q**

### CODE REVIEW

**Comment by alex-harvey-z3q** [comment]
Ping @lesaux

**Comment by lesaux** [comment]
Is there a requirement for dl timeout with the nanliu archive module as well?

**Comment by alex-harvey-z3q** [comment]
As far as I can see, the other archive modules don't offer this feature, so there's not much we can do.

**Comment by lesaux** [comment]
Thank you!

**Pull request merged**
