### PR TITLE
Add missing chown for the PID file.

### PR DESCRIPTION
**Pull request by alex-harvey-z3q**

### CODE REVIEW

**Comment by alex-harvey-z3q** [comment]
I've cleaned up a bit too.  Some notes:
- I used the `verify_contents` method of the Puppet Labs spec helper to add some tests.  It's a useful undocumented feature.  They really should document it.
- I resolved all the Rspec deprecation warnings relating to old style `should` syntax (although I didn't look at the Beaker tests).
- There is still a deprecation warning coming from the `verify_contents` method.  It's fixed in master but we're waiting on Puppet Labs to cut another release of the spec helper.
- I cleaned up the README.  Note that README was recommending deprecated `include ::kibana4` rather than `include kibana4`.  The issue that led to people sometimes using `include ::myclass` (dynamic scoping I think) is fixed in Puppet 4, and was always only an edge-case in Puppet 3.

**Comment by alex-harvey-z3q** [comment]
Sadly we end up with a warning in the Kibana log file:

``` json
{
  "type": "log",
  "@timestamp": "2016-04-25T07:23:31+00:00",
  "tags": [
    "pid",
    "warning"
  ],
  "pid": "14473",
  "path": "/var/run/kibana4/kibana4.pid",
  "message": "pid file already exists at /var/run/kibana4/kibana4.pid"
}
```

I'm not sure that we should be creating the PID file at all.

**Comment by alex-harvey-z3q** [comment]
Ping @lesaux

**Comment by lesaux** [comment]
Hi @alexharv074,

Thanks for the clean up efforts!

For the kibana warning in logs, I think we had that warning before too - I don't think it's a module problem.

I'll merge.

**Pull request merged**
