### PR TITLE
Make kibana 4.2 the default deployed version

### PR DESCRIPTION
**Pull request by walterheck**
Add support for kibana 4.2

This commit adds a bunch of stuff to work with kibana 4.2:
- the name of most kibana config parameters has changed in 4.2. The
  main class and params class support all new style config parameters
  (see: https://www.elastic.co/guide/en/kibana/4.2/kibana-server-properties.html)
- logging will now go to /var/log/kibana/kibana.log by default
- bundled_plugin_ids was removed and as such is also removed from this module

### CODE REVIEW

**Comment by lesaux** [comment]
wow this is really nice. I'll take a better look at it tonight, but I have a quick comment about the /etc/default/kibana4 file for the RedHat OsFamily which should preferably be /etc/sysconfig/kibana4 (I believe the init script sources either file)

**Comment by walterheck** [comment]
Ah yes, I guess that can be added in the params class with a case-statement checking osfamily.

**Comment by lesaux** [comment]
Sorry for the delay - I'll make a note to use /etc/sysconfig/kibana4

**Comment by lesaux** [comment]
oh, and thanks for the blacksmith additions.

**Pull request merged**
